In [1]:
!pip install numpy
import numpy as np


[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Exercício 1: Crie um array de 10 elementos. Altere o valores de todos os elementos
com índices 5 até 8 para 0.

In [21]:
vetor0 = np.arange(0,10,1)
print(vetor0)
for valor,idx in enumerate(vetor0):
    if idx >= 5 and idx < 8:
        vetor0[idx] = 0

print(vetor0)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 0 0 0 8 9]


Exercício 2: Crie um array com 3 linhas e 2 colunas. Depois imprima o shape e a 2a
linha da matriz.

In [28]:
vetor1 = np.array([[0,1],[2,3],[4,5]])
print(vetor1)
print(np.shape(vetor1))
print(vetor1[1])

[[0 1]
 [2 3]
 [4 5]]
(3, 2)
[2 3]


Exercício 3: Crie um array com 3 linhas e 2 colunas. Depois imprima a 2a coluna.

In [26]:
print(vetor1)
print(vetor1[:,1])

[[0 1]
 [2 3]
 [4 5]]
[1 3 5]


Exercício 4: Crie um array de com 4 linhas e 5 colunas. Depois imprima os elementos
da terceira linha da matriz.

In [16]:
vetor2 = np.array([list(range(0,5)),list(range(5,10)),list(range(10,15)), list(range(15,20))])
print(vetor2)
print(vetor2[2])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[10 11 12 13 14]


Exercício 5: Crie um array de com 4 linhas e 5 colunas. Depois imprima todos os
elementos da primeira e segunda linhas e segunda a terceira colunas.

In [17]:
print(vetor2[0:2,1:3])

[[1 2]
 [6 7]]


Exercício 6: Crie um array de com 4 linhas e 5 colunas. Depois imprima todos os
elementos da segunda e terceira linhas e primeira a terceira colunas.

In [18]:
print(vetor2[1:3,0:3])

[[ 5  6  7]
 [10 11 12]]
